#pragma once
#include <stdint.h>

/* 32..126 are the letters, 127 is a blank hole, 128..155 are the TILE glyphs -
 * our own shapes, generated by tools/font_tiles.py. */
extern const uint8_t font12x24[(155 - 32 + 1) * 24 * 2];
